modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="league_of_legends_beta"
version="1.0.0"
displayName="league of legends beta"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="FUGAMARKET, MCreator"

[[dependencies.league_of_legends_beta]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




